### ISSUE TITLE
Add X-Git-NotificationType header to differentiate between types of notifications

### ISSUE THREAD

**Issue by job** [git-multimail/git-multimail#104]
I've noticed that in our group of devs some people love the fact that the diff is emailed, others are only interested in the summary mails and don't want to see the diffs.

Would it be possible to add some kind of mail header that reflects the various types of notifications? People not interested in diffs could then easily filter away those messages:

Following are header suggestions:

```
X-Git-NotificationType: diff
X-Git-NotificationType: ref_changed_plus_diff
X-Git-NotificationType: ref_changed
```

`ref_changed_plus_diff` would cover the new 'fewer emails if single commit' from 18203d0d8a08873b0d5e6ff02c1fb185dadd57e4

**Comment by moy** [comment]
That would actually be rather easy to add: just modify the template strings (`*_HEADER_TEMPLATE =`) in `git_multimail.py`, re-run the tests, update the `.expect` file.

Can you give it a try?

**Comment by job** [comment]
Done!
