### ISSUE TITLE
Rendering of some (unorthodox) commit summaries is sub-ideal

### ISSUE THREAD

**Issue by pfalcon** [git-multimail/git-multimail#108]
We use git-multimail on mirror of https://github.com/gcc-mirror/gcc . Commit message there don't follow git guidelines, and are heritage of ChangeLog file format. There're commits like https://github.com/gcc-mirror/gcc/commit/75c3f230cd53f464ed35a069842447d577167969 which lead to git-multimail messages like:

~~~~
      from  75c3f23   	* genmatch.c (fprintf_indent): New function. 	(operand::gen_transform): Add indent parameter. 	(expr::gen_transform, c_expr::gen_transform, 	capture::gen_transform): Ditto and use fprintf_indent. 	(dt_node::gen, dt_node::gen_kids, dt_node::gen_kids_1): Ditto. 	(dt_operand::gen, dt_operand::gen_predicate, 	dt_operand::gen_match_op, dt_operand::gen_gimple_expr, 	dt_operand::gen_generic_expr, dt_simplify::gen): Ditto. 	(decision_tree::gen_gimple): Adjust calls and inde [...]
       new  853a01d   2015-07-09  Vladimir Makarov  <vmakarov@redhat.com>
~~~~

It would be to have an option to force usage of single first line as summary (vs git convention that summary is separate from details with a blank line, with an extreme case of summary being multi-line).

**Comment by pfalcon** [comment]
Well, and in my mail client 75c3f23's summary actually looks multiline.

**Comment by moy** [comment]
I guess truncating the summary line to ~70 characters could fix this. I won't have time to work on this soon, but it should be a minor patch to `generate_summaries`, either calling git with a format like `--format='%h %<(100,trunc)%s` and trimming trailing whitespaces after, or doing the elipsis from Python.

Don't hesitate to ask for help if you try to implement this.

**Comment by pfalcon** [comment]
Thanks for the hint, emailMaxLineLength seems to do what's needed without any patching. One caveat is that it appears to be a max complete email's line length, so max commit summary length will be smaller than number specified.

I also wanted to ask about reducing indentation before "from", "new", but checking the source, those are just right-justified action names, longest being "discards". Well... there's still possibility to save 3 spaces: "adds", "discards" can be replaced with just "add", "discard", field len then can be reduced to 8 to have still at least 1-space indent, and spacing between action name and abbreviated rev can be reduced to 1 space from 2. I don't know if such change would make sense to you, let me know if you do, and would accept patch. Thanks.

**Comment by moy** [comment]
> emailMaxLineLength seems to do what's needed without any patching

Indeed, I forgot about this one.

> One caveat is that it appears to be a max complete email's line length, so max commit summary length will be smaller than number specified.

If you set emailMaxLineLength to ~70 to 79, then the whole line will be of the right length. Isn't that sufficient?

> "adds", "discards" can be replaced with just "add", "discard"

There's also "omits". I don't have strong opinion on that, I'm not the one who implemented it. @mhagger, any thoughts? Actually, I would have written "added", "discarded", but that goes against saving spaces.

> spacing between action name and abbreviated rev can be reduced to 1 space from 2.

Would make sense to me.
