### ISSUE TITLE
Allow HTML in template messages

### ISSUE THREAD

**Issue by moy** [git-multimail/git-multimail#116]
Currently, we allow sending HTML with syntax coloring for patches for commit messages. It would be tempting to allow the template message to include actual HTML too (e.g. `<a href="...">View the code online</a>`), but currently all the content of the message is HTML-escaped, hence this is not possible.

**Comment by cmanley** [comment]
I suppose Python has a templating engine that's the equivalent of Smarty for PHP or Template-Toolkit for Perl. If so, then I think it'll be a good idea to move the templates into external files in which all the necessary escaping is done where needed. Then these files can be grouped together in subdirs representing themes/skins, letting the user select a non-default theme using a config variable. 
That offers the most flexibility for users without them having to edit the source code after each update.

**Comment by moy** [comment]
I'm reluctant to introducing new dependencies. git-multimail is meant to be installed on servers, and the property "just drop one file and you're done with the installation" can be a very important property.

We don't need anything complicated to implement this. Right now, git-multimail does the escaping. We just need to make the escaping conditional. We still have this issue open just because no one took the time to do it yet.

**Comment by cmanley** [comment]
That makes sense to keep it as 1 file. Perhaps Python Eggs can provide the best of both worlds though.

**Comment by moy** [comment]
Let's close this and continue the discussion on PR #140.
