### ISSUE TITLE
gitolite.rst could use some editing for clarity

### ISSUE THREAD

**Issue by pfalcon** [git-multimail/git-multimail#117]
Reading thru https://github.com/git-multimail/git-multimail/blob/master/doc/gitolite.rst , it might use some editing for clarity. Specific, first line/paragraph is a bit confusing:

> git-multimail supports gitolite natively. Setting up git-multimail on a gitolite 3 installation can be done like this:

"supports natively", what does that mean? Perhaps saying "has special support for gitolite (see "custom environment" in README)". Second sentence, ending with colon, seems like stray at all, given the following paragraph.

**Comment by moy** [comment]
I don't understand the issue with "supports natively". git-multimail can be used as a gitolite hook without any add-on, which corresponds to the definition of "native support" (e.g. https://en.wiktionary.org/wiki/native_support). Please, reopen if you have a more specific reason to change this.

I removed the second sentence.
