### ISSUE TITLE
Testing docs could provide more details

### ISSUE THREAD

**Issue by pfalcon** [git-multimail/git-multimail#122]
I spent some time figuring out got I can get to the actual email contents for a failed test - until finally figured out that I should comment out "cleanup" "test". Docs could mention that, or even better, don't delete test repo in case of failures (or if it's too hard, don't delete test repo at the end of test at all).

Also, what about providing more "unit" tests? For example, for #118, what I really need to test is that for both `commitList=''` and `commitList=none` result of Config.get_recipients() is the same.

Whereas what's available now are integration tests, which are, well, PITA to work with, as there're many restrictions, etc. For example, test repo has announceList set, add using command-line option -c just adds to it, so I cannot really test "empty string or single 'none'" behavior without tricks, which you (and whoever novice will look into it later) would certainly find *dirty* tricks. End result is that I can't really contribute a testcase with the changes for #118.

**Comment by moy** [comment]
> I should comment out "cleanup" "test"

The simplest is actually to run the tests with `--immediate` to stop at the first failure (hence skip the cleanup), or add a `test_pause` within the script.

Don't hesitate to ask questions when you encounter a point like this. Writing doc is not very motivating when I'm not sure someone reads it ;-).

>  don't delete test repo in case of failures (or if it's too hard, don't delete test repo at the end of test at all).

Actually, we should just use Sharness better. We currently cd out of the Sharness trash directory (for historical reasons, we did so before @richardhansen ported the testsuite to Sharness), but if we remained in the trash directory, I think Sharness would do the right thing wrt deleting it.

Patches welcome to fix the above points.

> Also, what about providing more "unit" tests?

Please do! We already have `test-env` (probably mis-named as of today, as it contains unit-tests for stuff other than environment) called by `unit-tests.t`, you can either add new unit-tests there or create a new unit-test file.

> I cannot really test "empty string or single 'none'" behavior without tricks

I don't get it. Just `git config multimailhook.commitList none`, do the test, and revert to the previous value. You even have a `save_git_config` function to do the save/restore part now. Several tests already do that.

The real painful part about black-box tests is that they are very slow, and that is a good reason to provide unit-tests.

**Comment by pfalcon** [comment]
> The simplest is actually to run the tests with --immediate

Where to see list of switches? I figured running a `*.t` directly with -v give verbose output, but it doesn't list options on -h or --help. I also read README of sharness, and it doesn't mention them either.

> We already have test-env (probably mis-named as of today, as it contains unit-tests for stuff other than environment) called by unit-tests.t

D'oh. I saw unit-tests.t, but couldn't figure how it works. I guess, by the end of day I grepped for test-env.py, whereas it's just test-env in the same dir. Will work on it.

> I don't get it. Just git config multimailhook.commitList none, do the test, and revert to the previous value.

How do I know "previous value"? Querying for it already gets boring, re-setting to current original value will hit someone later when original changes.

> save_git_config

That's better, essentially I thought that I would need to write one, and that's a bit steep curve for new contributor to test a trivial change ;-). Overall, I tried to look into newer email-content.t, and it doesn't have all the tricks used.

Thanks for all the hints!

**Comment by moy** [comment]
> Where to see list of switches?

Sharness -> README.git. I've submitted a PR to make it easier to discover: https://github.com/git-multimail/git-multimail

> that's a bit steep curve for new contributor to test a trivial change ;-).

You'll thank me when you start contributing to Git ;-). We use Sharness which is derived from Git's testsuite, so writing tests for git-multimail is essentially the same as writing some for Git.

But I agree that there's still room for improvement. The testsuite started as a set of semi-manual stuff, then it was scripted better, then ported to Sharness. There's still quite some "historical effect" and unneeded complexity in several places. I've already done quite a lot and I continue working on it, but again, patches more than welcome!

**Comment by moy** [comment]
> We currently cd out of the Sharness trash directory [...] but if we remained in the trash directory, I think Sharness would do the right thing wrt deleting it.

This is done in master.

**Comment by pfalcon** [comment]
> Sharness -> README.git. I've submitted a PR to make it easier to discover: mlafeldt/sharness#41

Thanks!

> We use Sharness which is derived from Git's testsuite

I figured that, thus avoiding dumb questions why it's used at all ;-). Still using sharness for "command-line" tests and something more direct for Python unittest might help, instead of redirecting everything thru sharness. (Would have helped, now that I figured it out it's no longer important, and I wouldn't call to do that with any priority. So, you can count votes other people may have on this. ;-))

> But I agree that there's still room for improvement. The testsuite started as a set of semi-manual stuff

That's well understood, and I'm happy that there's just a testsuite, after facing those issues in other bugs, I didn't even try to look for another alternative - I know having both written and Python and a testsuite are unlikely to be seen ;-).

**Comment by moy** [comment]
> Still using sharness for "command-line" tests and something more direct for Python unittest might help

Having a single entry point, `make`, for all automated tests is really a good thing. The Sharness layer below the unit-tests is really minimal (there's a bit of Python 3 related dirtiness that should eventually go away, but essentially it's a one-liner test_expect_success 'unit test' 'test-env').

**Comment by moy** [comment]
I think my changes in 3d278c5623f8b6aef78290e14085edfe338c97ff and the mlafeldt/sharness#41 address all concrete issues mentioned here. If not, reopen or open new specific bugs.

Thanks,
