### ISSUE TITLE
SourceForge merge requests are not triggering git-multimail.

### ISSUE THREAD

**Issue by edward-dauvergne** [git-multimail/git-multimail#135]
Is there an option to have merge requests trigger git-multimail to send out messages?  I have noticed that things are not quite right with SourceForge.  For the FlightGear project, here is our [commitlogs mailing list archive](https://sourceforge.net/p/flightgear/mailman/flightgear-commitlogs).  An example of a commit which did not produce a message is:

* [The original commit in a fork](https://sourceforge.net/u/edauvergne/flightgear/ci/524136d709680416ed7e1ef981bf9e50aba186eb/) (and [its branch](https://sourceforge.net/u/edauvergne/flightgear/ci/lat_lon_precision_fix_v3/tree/))
* [The merged merge request](https://sourceforge.net/p/flightgear/flightgear/merge-requests/23/).
* [The merged commit](https://sourceforge.net/p/flightgear/flightgear/ci/524136d709680416ed7e1ef981bf9e50aba186eb).

It could be that the problem is with the [Allura platform SourceForge uses to manage the merging from forks](https://sourceforge.net/blog/how-to-accept-merge-requests-with-one-click/), but I cannot see how this would not trigger git-multimail in a post-receive hook.

Cheers,
Edward

**Comment by edward-dauvergne** [comment]
For reference, this is the Python code behind the SourceForge merge request web interface 'Merge' action (as a permanent link):

* https://forge-allura.apache.org/p/allura/git/ci/47b6504ea0a0af95cc255e4743c948f01261024e/tree/ForgeGit/forgegit/model/git_repo.py#l116

The instructions seem pretty clear:

```python
    def merge(self, mr):
        g = self._impl._git.git
        # can't merge in bare repo, so need to clone
        tmp_path = tempfile.mkdtemp()
        tmp_repo = git.Repo.clone_from(
            self.full_fs_path,
            to_path=tmp_path,
            bare=False)
        tmp_repo = GitImplementation(Object(full_fs_path=tmp_path))._git
        tmp_repo.git.fetch('origin', mr.target_branch)
        tmp_repo.git.checkout(mr.target_branch)
        tmp_repo.git.fetch(mr.downstream_repo.full_fs_path, mr.source_branch)
        author = h.really_unicode(c.user.display_name or c.user.username)
        tmp_repo.git.config('user.name', author)
        tmp_repo.git.config('user.email', '')
        msg = u'Merge {} branch {} into {}\n\n{}'.format(
            mr.downstream_repo.url(),
            mr.source_branch,
            mr.target_branch,
            h.absurl(mr.url()))
        tmp_repo.git.merge(mr.downstream.commit_id, '-m', msg)
        tmp_repo.git.push('origin', mr.target_branch)
        shutil.rmtree(tmp_path, ignore_errors=True)
```

From this, I still have no idea why this does not trigger git-multimail.

**Comment by moy** [comment]
I have very little time for git-multimail these days (I will have more soon hopefully). Did you check that the post-receive hook was triggered? What I do to debug this kind of issues is to have a hook doing stg like

    #!/bin/sh
    echo "post-receive hook triggered with $@" >> /tmp/log.txt
    exec git_multimail.py "$@"

and look at `/tmp/log.txt`. If the hook is triggered and `git_multimail.py` doesn't work, then we'll have a hint on where to look at.

**Comment by edward-dauvergne** [comment]
After a long debugging and very slow period, it is clear that the SourceForge Allura platform is triggering the commit hooks.  So the problem is on the git-multimail side.  This will take a long time to chase down!

**Comment by moy** [comment]
> it is clear that the SourceForge Allura platform is triggering the commit hooks

If "commit hooks" is a typo for "post-receive hook", then indeed it is probably a git-multimail issue. But if not, then you are putting `git_multimail.py` on the wrong side. If I read correctly the code snippet above, Allura is creating a temporary clone in which the merge is performed and then the result is pushed to `origin`. This temporary clone is a "client" repo (there's no real distinction with Git, but say, the same kind of repo you get on your laptop when cloning), and `git_multimail.py` is meant to run on the "server-side" repo, i.e. the one which receives the push.

What exact arguments are given to `git_multimail.py`? What is its output? You probably want to check `git config -l`, and environment variables (output of `env`) before calling `git_multimail.py` too.

**Comment by edward-dauvergne** [comment]
I have added the following to the post-receive hook script:

```sh
#!/bin/bash

# The repository hook script base directory.
DIR="$(dirname "${BASH_SOURCE[0]}")"

echo `date`: "post-receive hook triggered with" $@ >> $DIR/git-multimail-debug.log

# Execute the git_multimail script.
if [ -x $DIR/git_multimail.py ]; then
  exec $DIR/git_multimail.py
fi
#!/bin/bash

# The repository hook script base directory.
DIR="$(dirname "${BASH_SOURCE[0]}")"

echo `date`: "post-receive hook triggered with" $@ >> $DIR/git-multimail-debug.log

# Execute the git_multimail script.
if [ -x $DIR/git_multimail.py ]; then
  exec $DIR/git_multimail.py
fi
```
This is the hooks/post-receive-user script - a constraint of the SF system.  From the log file, I see:

```
Fri Feb 12 11:23:36 UTC 2016: post-receive hook triggered with
Fri Feb 12 11:26:18 UTC 2016: post-receive hook triggered with
Tue Feb 16 16:29:15 UTC 2016: post-receive hook triggered with
Tue Feb 16 16:46:52 UTC 2016: post-receive hook triggered with
Tue Feb 16 19:22:40 UTC 2016: post-receive hook triggered with
```

The first and last 2 entries are my committed merge requests.  These didn't trigger git-multimail, but the other two normal commits did (for reference, see the "[Flightgear-commitlogs] [FlightGear]" entries at https://sourceforge.net/p/flightgear/mailman/flightgear-commitlogs/?viewmonth=201602).  So I'm looking into the code to see if there is a false assumption in git-multimail causing the commit email to be skipped.

**Comment by edward-dauvergne** [comment]
For reference, here is the output of `git config -l` from the SF shell backend:

```sh
[edauvergne@shell-22006 flightgear.git]$ git config -l
core.sharedrepository=2
core.repositoryformatversion=0
core.filemode=true
core.bare=true
core.sharedrepository=2
receive.denynonfastforwards=true
receive.denydeletes=true
multimailhook.mailinglist=flightgear-commitlogs@lists.sourceforge.net
multimailhook.envelopesender=flightgear-commitlogs@lists.sourceforge.net
multimailhook.commitlogopts=-C --stat -p --cc --format='SF URL:  http://sourceforge.net/p/flightgear/flightgear/ci/%H/%n%nCommit:    %H%nAuthor:    %aN%nCommitter: %cn%nDate:      %ad%n%n%s%n%n%b%n%N%n'
multimailhook.emailprefix=[FlightGear] 
multimailhook.commitlist=flightgear-commitlogs@lists.sourceforge.net
multimailhook.emailmaxlines=10000
```

I'm pretty sure there isn't a problem with the config.

**Comment by moy** [comment]
edward-dauvergne <notifications@github.com> writes:

> # Execute the git_multimail script.
> if [ -x $DIR/git_multimail.py ]; then
>   exec $DIR/git_multimail.py
> fi

You can try replacing this with

$DIR/git_multimail.py 2>&1 | tee -a $DIR/git-multimail-debug.log

to get the output in the log file. There's a DEBUG constant in the
source code of git_multimail.py, unfortunately it's used only in one
place, but you may want to add more debug statements.

> The first and last 2 entries are my committed merge requests. These
> didn't trigger git-multimail, but the other two normal commits did

What exactly does "trigger git-multimail" mean here?

Several things can happen:

* git-multimail is not called. I think we ruled this out.

* git-multimail is called, but decides that there's no email to send.

* git-multimail is called, sends messages, but the message gets filtered
  out later (anti-spam, mailing-list "subscribers only" filter, ...). I
  think you shouldn't eliminate this option too quickly.

**Comment by edward-dauvergne** [comment]
Cheers.  I've added the git_multimail.py output catching to the script.  The DEBUG constant will be quite helpful.  The only problem is that this issue is encountered about 10 times per year (I unfortunately cannot reproduce it locally).  For "trigger git-multimail", that is deliberately ambiguous as it is not 100% clear where the problem lies.  The git-multimail script is clearly called.  And I've thoroughly checked the Mailman mailing list settings and see nothing suspicious (normal git-multimail commit emails manage to get through, which is suspicious).  So it is very likely to be in git_multimail.py, but who knows.

**Comment by moy** [comment]
Hi,

Unfortunately, I'm unable to help on this bug. I plan to add features that should help, like #148 and #155.

I'm closing the bug, but feel free to reopen if you have more info.

**Comment by moy** [comment]
Could this be related to https://public-inbox.org/git/5795EB1C.1080102@nokia.com/, i.e. Git dieing before running the post-receive hook because the client bailed out at the wrong time?

BTW, #148 and #155 are now implemented, so you can activate logging and see what happens.

**Comment by edward-dauvergne** [comment]
This is still an issue.  From debugging, I guess this could be the issue:

```
Tue Oct 18 08:05:04 UTC 2016: post-receive hook triggered with
  File "/gitrepo/p/flightgear/flightgear.git/hooks/git_multimail.py", line 771
    values['contenttype'] = 'html' if self._contains_html_diff else 'plain'
                                    ^
SyntaxError: invalid syntax
```
On the SourceForge system, the Python version is:

> Python 2.6.6 (r266:84292, Jan 22 2014, 09:42:36) 
 [GCC 4.4.7 20120313 (Red Hat 4.4.7-4)] on linux2

I wonder if this might be fixed in newer versions?

**Comment by moy** [comment]
Strange : the `...  if ... else ...`construct is Python 2.5+ only so I would bet you are running git-multimail with Python 2.4 (are you sure you don't have multiple Python installs or some load balancing across multiple machines with different Python versions?)

I test every release with Python 2.4, but only releases so I sometimes introduce incompatibilities with Python 2.4 and fix them before release. IOW: should be fixed.

**Comment by edward-dauvergne** [comment]
I'll try the newer version (the test suite is not passing for the 1.4.0 tag, but it doesn't seem critical).  The newer version doesn't use this type of ```if``` construct in this instance.  The only Python version I see in the SourceForge backend is 2.6.6, but maybe their shell services system runs a different Python to their git backend, as that is the exact error from Python 2.4 or earlier:

```
$ python2.4
Python 2.4.6 (#1, Oct  2 2012, 00:06:17)                                                                                                                                                                           
[GCC 4.5.2] on linux2                                                                                                                                                                                              
Type "help", "copyright", "credits" or "license" for more information.                                                                                                                                             
>>> a = 'html' if True else 'plain'                                                                                                                                                                                
  File "<stdin>", line 1                                                                                                                                                                                           
    a = 'html' if True else 'plain'                                                                                                                                                                                
                ^                                                                                                                                                                                                  
SyntaxError: invalid syntax                                                                                                                                                                                        
>>>
```

I might first add a printout of the Python version in the debugging log though (it might take a few days or longer for the script to be triggered).  If the version is 2.4, then maybe there will be other issues with the script.
