### ISSUE TITLE
Exception 'SMTPServerDisconnected'

### ISSUE THREAD

**Issue by seenupatri** [git-multimail/git-multimail#136]
I got the below exception, can you please let me know what I am doing wrong

remote: git-multimail version 1.3.dev
remote: Python version 2.7.6 (default, Mar 22 2014, 22:59:56) 
remote: [GCC 4.8.2]
remote: Traceback (most recent call last):
remote:   File "hooks/post-receive", line 3747, in main
remote:     run_as_post_receive_hook(environment, mailer)
remote:   File "hooks/post-receive", line 3414, in run_as_post_receive_hook
remote:     push.send_emails(mailer, body_filter=environment.filter_body)
remote:   File "hooks/post-receive", line 3352, in send_emails
remote:     rev.recipients,
remote:   File "hooks/post-receive", line 1989, in send
remote:     self.smtp.quit()
remote:   File "/usr/lib/python2.7/smtplib.py", line 756, in quit
remote:     res = self.docmd("quit")
remote:   File "/usr/lib/python2.7/smtplib.py", line 386, in docmd
remote:     self.putcmd(cmd, args)
remote:   File "/usr/lib/python2.7/smtplib.py", line 336, in putcmd
remote:     self.send(str)
remote:   File "/usr/lib/python2.7/smtplib.py", line 328, in send
remote:     raise SMTPServerDisconnected('please run connect() first')
remote: SMTPServerDisconnected: please run connect() first
remote: Exception smtplib.SMTPServerDisconnected: SMTPServerDisconnected('please run connect() first',) in <bound method SMTPMailer.__del__ of <__main__.SMTPMailer object at 0x7f6dca4a3950>> ignored

**Comment by moy** [comment]
Can you post the corresponding section of your configuration file (removing password if applicable obviously)?

**Comment by seenupatri** [comment]
[multimailhook]
    showrev = "git show -C %s; echo"
    emailprefix = "[git-projectname] "
    mailinglist = "kumarp@mycompany.com"
    envelopesender = pradeepk@mycompany.com
    mailer = smtp
    smtpServer = "smtp.office365.com:587"
    smtpUser = "pradeepk@mycompany.com"
    smtpPass = "xxxxxxxx"
    smtpEncryption = "tls"

**Comment by moy** [comment]
Can you reproduce the issue with other SMTP servers like the one of gmail?

**Comment by moy** [comment]
You did not copy-paste the whole message. The lines above should look like

    *** Error sending email ***
    *** SOMETHING HERE

The backtrace you are seeing is git-multimail trying to close the connection after something went wrong, and I cannot debug that without knowing. It is possible that you just entered an incorrect username or password.

**Comment by moy** [comment]
I've just pushed a0219db300d763ccddec410657 which should make the message clearer (but not fix the root of your problem).

**Comment by moy** [comment]
Just a ping, @seenupatri : can you try with the latest version, and give the full error message?

Without further information I can't do anything, so I'll close the issue if you can't provide more info.

Thanks,

**Comment by moy** [comment]
As explained before, I can't do anything without further information. I'm closing the issue. Feel free to reopen if you can provide more info.
