### ISSUE TITLE
git-multimail seems to take forever to run

### ISSUE THREAD

**Issue by dale-c-anderson** [git-multimail/git-multimail#138]
We have it set up on a post-receive hook, and lately the mailer takes upwards of 30 seconds to do its processing. No noticeable extra disk or cpu activity while it's running. Just seems to take its sweet time for no reason. A manual test of mail from the command line shows instant delivery to the local MTA. 

Changing the number of recipients seems to make no difference.

Is there any kind of debugging or logging that can be enabled to find out what's taking so long?

**Comment by moy** [comment]
Hi,

There's not much debug or log features in `git_multimail.py` as of now. There's a `DEBUG` constant in the code, but used just once (patches welcome to add more usages).

When you say "manual test", do you mean "running `git_multimail.py` by hand", or running another command to send an email? Try launching `git_multimail.py` by hand on the exact same condition as when it's launched by the hook. Try with `strace python git_multimail.py` (if possible interactively, but you can add `strace` to your hook if it doesn't work). If there's no particular activity, then most likely these 30 seconds are a timeout waiting for something, and `strace` should be able to tell you.

**Comment by moy** [comment]
Oh, I forgot: try adding `--stdout` to the command line, and see if the delay disappears. If so, it's a delay when sending the email (that would be my guess), if not it's while generating the email.

**Comment by dale-c-anderson** [comment]
When I say manual test, I mean just running `echo "foo" | mail -s "subject" user@example.com'.

Appending `--stdout` seems to make no difference.  Our hook is the [post-receive example](https://github.com/git-multimail/git-multimail/blob/master/git-multimail/post-receive.example), if that matters.

When running with strace, it pauses at the spot below where I had time to enter a couple of line breaks while it was running: 

<snip>
`
write(4, "\n", 1)                       = 1
write(4, "-- \n", 4)                    = 4
write(4, "To stop receiving notification e"..., 68) = 68
write(4, "the administrator of this reposi"..., 38) = 38
close(4)                                = 0
wait4(429, 

` at this point things paused, and I had time to go check my mail `

[{WIFEXITED(s) && WEXITSTATUS(s) == 0}], 0, NULL) = 429
--- SIGCHLD (Child exited) @ 0 (0) ---
pipe([3, 4])                            = 0
fcntl(3, F_GETFD)                       = 0
fcntl(3, F_SETFD, FD_CLOEXEC)           = 0
fcntl(4, F_GETFD)                       = 0
`
</snip>

**Comment by moy** [comment]
Why are you using `post-receive.example` instead of just `git_multimail.py`? Indeed, the custom hook doesn't look at command-line options.

Instead of trying `mail`, try `sendmail -oi -t` which is what `git_multimail.py` uses internally by default.

I suspect the `wait4` in your trace corresponds to the `p.wait()` statement at the end of `SendMailer` class. Can you check that by adding debug statements before and after?

**Comment by dale-c-anderson** [comment]
The delay is definitely with our mail system, and not with the script. Using sendmail at the command line was also slow as molasses. Thanks for the tips, Moy.
