### ISSUE TITLE
Please implement showrev for commit links

### ISSUE THREAD

**Issue by cmanley** [git-multimail/git-multimail#139]
As implemented in https://github.com/git/git/blob/master/contrib/hooks/post-receive-email

I've never done anything with Python before, but I tried to patch git_multimail.py myself.
The script compiles ok, but when used by the post-receive example script, I get the exception "*** Error while generating commit email". I have no idea why, but these are my changes to the release 1.2 code in case it's of any use:

The diff (in function generate_email()):
```python
--- git_multimail.orig.py       2016-02-18 22:58:56.704717229 +0100
+++ git_multimail.py    2016-02-18 23:24:01.194336451 +0100
@@ -899,6 +899,7 @@
                 # that looks like it might be part of a diff.
                 bgcolor = ''
                 fgcolor = ''
+                commit_line = ''
                 if line.startswith('--- a/'):
                     diff_started = True
                     bgcolor = 'e0e0ff'
@@ -916,9 +917,16 @@
                         bgcolor = 'ffe0e0'
                 elif line.startswith('commit '):
                     fgcolor = '808000'
+                    p = re.compile('^(commit\s+)([a-f\d]{40})\s*$')
+                    m = p.match(line);
+                    if (m):
+                        commit_line = m.groups(1) + '<a href="http://my_server.com/gitlist/MyProject.git/commit/' + m.groups(2) + '">' + m.groups(2) + '</a>';
                 elif line.startswith('    '):
                     fgcolor = '404040'
 
+                if commit_line:
+                    line = commit_line
+                else:
                 # Chop the trailing LF, we don't want it inside <pre>.
                 line = cgi.escape(line[:-1])
```

As you can see, I hard coded my website URL into the patch. It would be nice if the URL can be specified in a config variable with %s where the SHA1 string must placed.

For gitlist such a config setting could be something like:
multimailhook.url=http://my_server.com/gitlist/MyProject.git/commit/%s
and for gitweb:
multimailhook.url=http://my_server.com/gitrepo/?p=MyProject;a=commitdiff;h=%s

**Comment by moy** [comment]
Please use pull-requests instead of issues when posting code. Even if the code is not mergeable as-is, it's more convenient to use. Your code cannot be included without your sign-off (please read https://github.com/git-multimail/git-multimail/blob/master/CONTRIBUTING.rst).

It would be nice to have an easier way to do this, but what you're looking for is already possible with templates: override `REFCHANGE_INTRO_TEMPLATE` and include something like `http://my_server.com/gitlist/MyProject.git/commit/%(newrev)s` to generate a link. Proper HTML is another issue until #116 is implemented.

**Comment by cmanley** [comment]
Thanks for the tip. I've got the link in there now. It's not clickable though, but it's a step forward.

**Comment by moy** [comment]
Pull request #140 should allow you to get a clickable link. There's even some [documentation](https://github.com/git-multimail/git-multimail/blob/html-in-intro/doc/customizing-emails.rst).

Feedback welcome.

**Comment by cmanley** [comment]
Thanks. I got it working now with links for gitweb and gitlist, using the documentation link you provided (and an added "import sys" line).

**Comment by moy** [comment]
Indeed. I added the import sys in the doc.

I'm keeping the bug open since it'd be nice to have a simple config-based mechanism, but I won't work on that soon.
