### ISSUE TITLE
Rewrite the from address to post on a mailing-list

### ISSUE THREAD

**Issue by sdouche** [git-multimail/git-multimail#152]
Hi,
I tried to set a fixed address (from, fromCommit and fromRefchange options) but it use always the committer address. The goal is to post on a mailling list w/o subscribe all developers.

 What am I doing wrong?

**Comment by moy** [comment]
First, make sure that git-multimail is actually using the address you think. I've started a FAQ here: https://github.com/git-multimail/git-multimail/blob/master/doc/troubleshooting.rst

If the FAQ is not sufficient, can you post the output of

    git config -l | grep multimailhook

(anonimize as needed the right hand-side of `=`, but keep the variable names unchanged)?

**Comment by moy** [comment]
@sdouche: just a ping: did the FAQ help you solve the issue? If not, please post more details (and/or suggest FAQ improvements). Without further info, I'll close the bug.

Cheers,

**Comment by sdouche** [comment]
Hi @moy,
sorry for the lag. I don't understand your FAQ. My goal is to replace the committer's address by a fixed one (like ci@mycompany.com).

BTW, I found an workaround (I accept all people from the company).

**Comment by moy** [comment]
>  I don't understand your FAQ

Which part do you not understand? (real question: the goal is to clarify what's not clear)

> My goal is to replace the committer's address by a fixed one (like ci@mycompany.com).

git-multimail sends emails, which have no notion of "commiter". Do you want to set the `From` field, or the sender?

**Comment by moy** [comment]
Feel free to reopen if you have more info.
