### ISSUE TITLE
combineWhenSingleCommit ignores commitBrowseURL

### ISSUE THREAD

**Issue by marcnarc** [git-multimail/git-multimail#154]
Config:

- mailingList = list1@example.com
- commitList = list2@example.com
- commitEmailFormat = html
- combineWhenSingleCommit = true
- commitBrowseURL = "http://example.com/git?commit=%(id)s"

When the push consists of a single commit, the single combined message is HTML-formatted but lacks the commitBrowseURL link.

**Comment by moy** [comment]
Indeed, I didn't test this case. The fix should be essentially a matter of moving `generate_browse_link` to the right class. Patches welcome, or I'll try to fix that myself (no guarantee on timing)..

**Comment by moy** [comment]
This should be fixed in branch 1.3 (66bcd1510d3470313a151a90a63caa0b11968dc2). @marcnarc, can you test it?

Thanks,

**Comment by marcnarc** [comment]
Yup, it's fixed.  Thanks @moy!
