### ISSUE TITLE
Truncate Long Subject Lines

### ISSUE THREAD

**Issue by dravster** [git-multimail/git-multimail#165]
In the environment I work in, we use long commit messages (detailing files changed,
changes made and rantionale). We recently switched from to using git-multimail, however
one issue that has arisen is that we now have Subject: lines often in the thousands of characters.

Is it possible to have an option to truncate [...] subjects over a certain length?

I'm trying to look to do this, but I've really not used python much!

**Comment by moy** [comment]
Hi,

`multimailhook.emailMaxLines` should be close to what you are looking for (may help you write a patch). I'm essentially offline until mid-august, but I'll probably try implementing this if you didn't manage.

That said, I don't understand your need for long _subject_ lines. Sure, having long commit messages is good, but the subject line is just the first line of the commit (separated from the rest of the commit message with a blank line). Commit messages are to be written just like emails: a short subject line and then a body as long as you need (read `man git-commit` for more info). Adopting this convention will not only make git-multimail friendlier, but also essentially any history navigation tool (`git log --oneline`, `gitk`, ...).

**Comment by dravster** [comment]
I imagine the "leaving a blank line" will be the magic to stopping it in the short term (we've never put that gap in the commit messages). It may be worth doing a patch that splits the commit message on
the first newline rather than chunking the lines together and truncating? I hopefully will get some time to look at the patch this week. Thanks for the respone :)

**Comment by moy** [comment]
Splitting the subject line at the first blank line is how Git works. Changing that in git-multimail would be a hack and wouldn't benefit users in the long run IMHO, since it would encourage bad practices that would make other tools run badly. 

Adopting git's convention is not just a short term workaround for you, it's just working with Git the way it was designed.

**Comment by dravster** [comment]
Okay no problem, I'll look at the MaxLines change then (and thanks for the info on convention, I had no idea :)

**Comment by moy** [comment]
Did you start anything? If not, I can work on a patch soon (I want to release git-multimail 1.4 this week, why not get this in the release ...).

**Comment by dravster** [comment]
Hi,

I had a brief look, but didn't get very far (I've had a busy week!). Sorry about that!

**Comment by moy** [comment]
OK, patch coming soon.

**Comment by moy** [comment]
OK, implementation available in #168. Can you please test it?
