### ISSUE TITLE
git-multimail cannot find recipients in gitolite setting

### ISSUE THREAD

**Issue by norbusan** [git-multimail/git-multimail#179]
Dear all,
I am struggling with setting up git-multimail, it never finds any recipients. In my case I am using gitolite and have the following setup:

- `.gitolite/hooks/common/post-receive` contains only `exec /home/git/git-multimail/git-multimail/git_multimail.py --stdout "$@"` where this is the git checkout
- `.gitolite.rc` contains `GIT_CONFIG_KEYS                 =>  '.*',`
- configuration in `gitolite-admin.git/conf/gitolite.conf`:
```
repo @all
    config multimailhook.environment = gitolite

repo gitolite-admin
    RW+     =   usera
    config multimailhook.mailingList  = 'aaa@bbb.ccc'
    config multimailhook.emailprefix  = '[gitolite-admin commit] '
    config multimailhook.from = 'git repo activity <git@bla.bla>'

repo foobar
    RW+      = usera
    config multimailhook.mailinglist  = 'aaa@bbb.ccc'
    config multimailhook.emailprefix  = '[git:foobar] '
    config multimailhook.from = 'git repo activity <git@bla.bla>'

```

In this case I get two errors:
- when pushing to the repo foobar, I get `remote: No email recipients configured!`
- when pushing to the gitolite-admin repo, I also get the following errors: `FATAL: bad config value 'git repo activity <git@bla.bla>'`

In the gitolite log file I see:
```
2017-03-28.21:26:08	26447		system,gitolite compile
2017-03-28.21:26:08	26447	die	bad config value 'git repo activity <git@bla.bla>'
2017-03-28.21:26:08	26447		system() failed,gitolite compile,-> 6400
```

Since normal gitolite is working without any problem (pushing, pulling etc), I assume there is a problem with mutlimail.

I tried also the debug method with setting `GIT_MULTIMAIL_CHECK_SETUP=true ...` but got the same `No email recipients configured!`

Thanks for any suggestion!

All the best

Norbert

**Comment by norbusan** [comment]
Argg, the syntax 'NAME <EMAIL@FOO.BAR>' is caught by gitolite's UNSAFE_PATT, only plain emails can be entered.

After this everything works.

Sorry for the noise.

**Comment by moy** [comment]
Don't apologize for the noise, it did deserve being documented here and I just did so :-).

**Comment by norbusan** [comment]
Well, thanks, if it served someone else, too, it's good.
