### ISSUE TITLE
Script wont run in bare repository

### ISSUE THREAD

**Issue by LovesTha** [git-multimail/git-multimail#180]
I have two repositories on my server, one is a bare repository and the other isn't. Both appear to run multimail.py but the bare one doesn't send the emails and the other does.
 
git config --all for both repositories on the server:

> git config --list
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
core.sharedrepository=group
multimail.reponame=A Nonbare Repository
multimail.mailinglist=Gareth Pye <garethp@sample.com>
multimail.commitemailformat=html
multimail.administrator=Gareth
multimail.administrator=Gareth
multimailhook.envelopesender=garethp@sample.com
multimailhook.smtpserver=mail.sample.com
multimailhook.smtpuser=garethp@sample.com
multimailhook.smtppass=<real password>
multimailhook.smtpencryption=tls
multimailhook.mailinglist=garethp@sample.com
multimailhook.mailer=smtp
multimailhook.smtpserverdebuglevel=3

> git config --list
core.repositoryformatversion=0
core.filemode=true
core.bare=true
core.sharedrepository=group
multimail.reponame=A Bare Repository
multimail.mailinglist=Gareth Pye <garethp@sample.com>
multimail.commitemailformat=html
multimail.administrator=Gareth
multimailhook.envelopesender=garethp@sample.coim
multimailhook.smtpserver=mail.sample.com
multimailhook.smtpuser=garethp@sample.com
multimailhook.smtppass=<real password>
multimailhook.smtpencryption=tls
multimailhook.mailinglist=garethp@sample.com
multimailhook.mailer=smtp
multimailhook.smtpserverdebuglevel=10

And the relevant part of a push to each repository:

Total 3 (delta 2), reused 0 (delta 0)
remote: *** Warning, the server certificat is not verified (smtp) ***
remote: ***          set the option smtpCACerts                   ***
remote: 
remote: Sending notification emails to: garethp@sample.com
remote: send: 'AUTH PLAIN <snip>\r\n'
remote: reply: '235 Authentication succeeded\r\n'
<lots more snipped with plusibly sensitive stuff, lets say it looks like a normal smtp debug log>
remote: reply: retcode (221); Msg: mail.sample.com closing connection
remote: *** Setting debug on for SMTP server connection (10) ***
To projects.sample.com:/git/Nonbare

Total 3 (delta 1), reused 0 (delta 0)
remote: Sending notification emails to: garethp@sample.com
To projects.sample.com:/git/Bare

Both repositories have a boring link in hooks:
post-receive -> /usr/local/bin/git_multimail.py

Is there something I'm missing, I can't believe this is a bug. But I can't find anything to explain the behaviour.

**Comment by moy** [comment]
You have a suspicious `multimail.mailinglist`. Try with just `garethp@sample.com` and `Gareth Pye <garethp@sample.com>` (with the `<>` brackets).

About bare repos, I can tell you that I use git-multimail in bare repos daily and I don't remember seeing a report about an issue with bare repos, so I don't think that's the issue.

Please, check [troubleshooting.rst](https://github.com/git-multimail/git-multimail/blob/master/doc/troubleshooting.rst) (post the result of `GIT_MULTIMAIL_CHECK_SETUP=true`, it may help).f

Also, if possible, check your mail server's log. It is likely that git-multimail does send the emails (you do see the SMTP trace in both cases, right?), but the emails are blocked somewhere else. Obviously, check your spam folder.

**Comment by LovesTha** [comment]
No, only the non-bare repo shows the SMTP trace. The bare repository (with smtp debug set) only says:

remote: Sending notification emails to: garethp@sample.com

Nothing of the debug info shown.

**Comment by LovesTha** [comment]
PS: the address is with the angle brackets, I just haven't fixed the formatting to show that :)

**Comment by LovesTha** [comment]
Comparing the output of GIT_MULTIMAIL_CHECK_SETUP=true /usr/local/bin/git_multimail.py in the two repo directories on the server gives me just 3 difference, all of which are the repositories name related. But still actually pushing to them gets completely different outcomes with only the non-bare repository giving me smtp debug information or emails turning up

**Comment by LovesTha** [comment]
Oh I tried the boring pure email address options as well, no change.

**Comment by LovesTha** [comment]
the problem must be something around the recipient list as the one that work prints:
remote: Sending notification emails to: garethp@sample.com
and the one that does nothing prints:
remote: Sending notification emails to: garethp@sample.com, garethp@sample.com

**Comment by LovesTha** [comment]
And now I'm going to slink off into a corner and remember that I needed to explicitly push my test branch....

**Comment by LovesTha** [comment]
That said saying 'now sending emails to X, Y@sample.com' is confusing when there is no intent to send emails to those users.

**Comment by moy** [comment]
I don't understand what exactly was your problem. Is it #157, or a variant of it? Feel free to open an issue with the precise problem (expected and actual behavior).

**Comment by LovesTha** [comment]
Will do.

**Comment by LovesTha** [comment]
I would do if I could manage to replicate it. Something was broken in what I thought I was doing.
