### ISSUE TITLE
Check and fix or ignore LGTM warnings

### ISSUE THREAD

**Issue by moy** [git-multimail/git-multimail#184]
https://lgtm.com/projects/g/git-multimail/git-multimail/alerts/?mode=list

Many of them are false-positive due to the mixin pattern (`super` does not call the superclass but the next class in the list), but there seem to be valid concerns to be fixed.

**Comment by sjvs** [comment]
Maybe @markshannon can help with the FPs?

(full disclosure: we're both part of the team that built LGTM.com :slightly_smiling_face:)

**Comment by sjvs** [comment]
Hi @moy: the FPs you reported were resolved a while ago. That's the nice thing about all of our analyses being implemented as [queries](https://github.com/Semmle/QL) that can be improved easily! Let me know if you have any further suggestions.

**Comment by moy** [comment]
Cool, thanks for the update. Now, it's my turn to work on fixing the actual positives ;-).
