### ISSUE TITLE
Put user-mailaddress mappings in a separate file

### ISSUE THREAD

**Issue by Farom** [git-multimail/git-multimail#187]
https://github.com/git-multimail/git-multimail/blob/6d19ac2dd3e1e62a9862021d803a60f197c102d7/git-multimail/git_multimail.py#L3195

when finding the gitolite user <-> email mapping in gitolite config, only the 'gitolite.conf' is searched.

I have multiple gitolite instances and it would minimize my settings to have either the gitolite.conf parsed 
with includes or search the mapping in a well known file like 'conf/user-mailaddress-map'.

I could prepare a pull request, which solution would you prefer to pull?
I'd prefer the simple one with searching in a  well known file.

**Comment by moy** [comment]
Hi, and sorry for the late reply.

I don't use gitolite myself, so I'm not sure which is best from the user's point of view. Maybe @rhansen who wrote the email mapping code has something to say.

I don't understand what you mean by "well known file". If I understand correctly, you'd want a different file for each gitolite instance? Do you mean that you'd replicate the `conf/user-mailaddress-map` to all your instances, but keep `gitolite.conf` different in each instance?

**Comment by Farom** [comment]
First: Sorry for the late reply ... i had great holidays this year :-)

You have understood me correctly. If i put all Mappings to the file _conf/user-mailaddress-map_ I could synchronize this file to each instance.

**Comment by moy** [comment]
OK. I think this is something meant for advanced configuration, so I suggest we implement this by having a config variable, say `multimailhook.MailaddressMap` unset by default (when unset, git-multimail would keep working as it is now). When set, `multimailhook.MailaddressMap` should point to a file. Then, git-multimail would would search this file in addition to `gitolite.conf`. So one could e.g.

```
repo @all
    config multimailhook.MailaddressMap = ~/.gitolite/conf/user-mailaddress-map
```

and then put the addr map the file. When hosting several projects in the same instance, the address map could also be per-repository (and possibly shared between several repositories).

I'm not sure what to do when the path is relative. I'd make it relative to `~/gitolite/conf` (AKA `GL_CONF` in git-multimail's source code), but another option is to make it relative to the repository being pushed to (it's a bare repository and the user doesn't have direct access to it, so there's not much interesting there).

**Comment by moy** [comment]
Oh, and the `BEGIN USER EMAILS` and leading `#` wouldn't make much sense in this file, so `multimailhook.MailaddressMap` would just contain the uncommented entries. For cut-and-pastability, I think I'll make it ignore leading `#` and `BEGIN/END USER EMAILS` lines so that the format in `gitolite.conf` is also accepted.
