### ISSUE TITLE
Exception 'UnicodeEncodeError'

### ISSUE THREAD

**Issue by sandynomad** [git-multimail/git-multimail#209]
remote: Exception 'UnicodeEncodeError' raised. Please report this as a bug to
remote: https://github.com/git-multimail/git-multimail/issues
remote: with the information below:
remote: 
remote: git-multimail version 1.4.0
remote: Python version 3.6.8 (default, Nov 21 2019, 19:31:34) 
remote: [GCC 8.3.1 20190507 (Red Hat 8.3.1-4)]
remote: Traceback (most recent call last):
remote:   File "/srv/git/puppet6.git/hooks/post-receive.d/git_multimail", line 4214, in main
remote:     run_as_post_receive_hook(environment, mailer)
remote:   File "/srv/git/puppet6.git/hooks/post-receive.d/git_multimail", line 3669, in run_as_post_receive_hook
remote:     push.send_emails(mailer, body_filter=environment.filter_body)
remote:   File "/srv/git/puppet6.git/hooks/post-receive.d/git_multimail", line 3596, in send_emails
remote:     rev.recipients,
remote:   File "/srv/git/puppet6.git/hooks/post-receive.d/git_multimail", line 2146, in send
remote:     self.smtp.sendmail(self.envelopesender, to_addrs, msg)
remote:   File "/usr/lib64/python3.6/smtplib.py", line 855, in sendmail
remote:     msg = _fix_eols(msg).encode('ascii')
remote: UnicodeEncodeError: 'ascii' codec can't encode character '\xfc' in position 2338: ordinal not in range(128)

**Comment by moy** [comment]
Thanks for the report, and sorry for the delay. Do you have any way to reproduce this issue? Does the testsuite pass on the machine where you get the bug?

We have tests for non-ascii characters in almost every possible place (AFAIK, only accents in the email adress are not supported), so I'm short of idea to trigger the bug on my side...

Thanks,

**Comment by sandynomad** [comment]
Ah. Had to stop using git-multimail because of this issue. I'll see if the original issue can be replicated again.

**Comment by xsuchy** [comment]
I have this issue as well. You can reproduce this issue when try to push commit with:

```
Author: Miroslav Suchý <msuchy@redhat.com>
```
The accented "y" will cause this.

**Comment by fcami** [comment]
This is due to SMTPlib using ascii by default for from/to addresses:
https://docs.python.org/3/library/smtplib.html

**Comment by ynezz** [comment]
> This is due to SMTPlib using ascii by default for from/to addresses:

Nope, it chokes on `msg = _fix_eols(msg).encode('ascii')` which is message body, so usually `Signed-off-by:` tags and such.

**Comment by ynezz** [comment]
Seems to fix it for me:

```diff
diff --git a/git-multimail/git_multimail.py b/git-multimail/git_multimail.py
index 7aca6c9..dc97d6e 100755
--- a/git-multimail/git_multimail.py
+++ b/git-multimail/git_multimail.py
@@ -2194,7 +2194,7 @@ class SMTPMailer(Mailer):
             # turn comma-separated list into Python list if needed.
             if is_string(to_addrs):
                 to_addrs = [email for (name, email) in getaddresses([to_addrs])]
-            self.smtp.sendmail(self.envelopesender, to_addrs, msg)
+            self.smtp.sendmail(self.envelopesender, to_addrs, msg.encode('utf8'))
         except socket.timeout:
             self.environment.get_logger().error(
                 '*** Error sending email ***\n'
```

**Comment by moy** [comment]
> Seems to fix it for me:
> 
> ```diff
> diff --git a/git-multimail/git_multimail.py b/git-multimail/git_multimail.py
> index 7aca6c9..dc97d6e 100755
> --- a/git-multimail/git_multimail.py
> +++ b/git-multimail/git_multimail.py
> @@ -2194,7 +2194,7 @@ class SMTPMailer(Mailer):
>              # turn comma-separated list into Python list if needed.
>              if is_string(to_addrs):
>                  to_addrs = [email for (name, email) in getaddresses([to_addrs])]
> -            self.smtp.sendmail(self.envelopesender, to_addrs, msg)
> +            self.smtp.sendmail(self.envelopesender, to_addrs, msg.encode('utf8'))
>          except socket.timeout:
>              self.environment.get_logger().error(
>                  '*** Error sending email ***\n'
> ```

Applied, thanks. To others: can you confirm that the bug is actually fixed now?
