### ISSUE TITLE
Crashes using nonexistent SSLFakeFile with Python 3.3+, mailer=smtp, smtpEncryption=tls

### ISSUE THREAD

**Issue by brettcs** [git-multimail/git-multimail#215]
With the settings described, git-multimail crashes with:

```
*** Error establishing SMTP connection to SERVER:587 ***        
*** module 'smtplib' has no attribute 'SSLFakeFile'        
```

[smtplib.SSLFakeFile was removed in Python 3.3](https://docs.python.org/3.3/whatsnew/3.3.html):

> The undocumented internal helper class SSLFakeFile has been removed from smtplib, since its functionality has long been provided directly by socket.socket.makefile().

I'm guessing the code should be updated to use that new socket method.

**Comment by moy** [comment]
Does #216 work for you?

**Comment by brettcs** [comment]
Sorry for the delay in getting back to you. The PR as-is fails with this error:

```
*** Error establishing SMTP connection to SERVER:587 ***
*** strip arg must be None or str

Exception ignored in: <function SMTPMailer.__del__ at 0x7f5772d56488>
Traceback (most recent call last):
  File "hooks/post-receive", line 2185, in __del__
    self.close()
  File "hooks/post-receive", line 2181, in close
    self.smtp.quit()
  File "/usr/lib/python3.7/smtplib.py", line 984, in quit
    res = self.docmd("quit")
  File "/usr/lib/python3.7/smtplib.py", line 421, in docmd
    return self.getreply()
  File "/usr/lib/python3.7/smtplib.py", line 400, in getreply
    resp.append(line[4:].strip(b' \t\r\n'))
TypeError: strip arg must be None or str
```

It works if you pass `'rb'` as the first mode argument to the new makefile() call. Apparently smtplib expects that file to return binary. Even though this exception happens in `__del__`, looking at the mail server logs the server apparently considers this a connection failure and does not queue the mail.

Thanks!

**Comment by moy** [comment]
I've updated the PR, can you confirm that it's OK now?

**Comment by brettcs** [comment]
Yup, that's good, thanks!
