### ISSUE TITLE
 Confused about release tags

### ISSUE THREAD

**Issue by yuzibo** [git-multimail/git-multimail#223]
hi，
I noticed that https://github.com/git-multimail/git-multimail/releases
and [Release 1.5.0](https://github.com/git-multimail/git-multimail/releases/tag/1.5.0) is the latest release, but tag page has a 1.6.0: https://github.com/git-multimail/git-multimail/releases/tag/1.6.0. So i should package it with 1.6.0?

**Comment by anarcat** [comment]
i'd say package 1.6.0, it doesn't matter if it's a release or a tag, it's essentially the same as far as debian's concerned.

this bug report can be closed, i think.

**Comment by moy** [comment]
Indeed, i just forgot to create the github release, but you can use the 1.6 tag.

**Comment by yuzibo** [comment]
yeah. I am choosing 1.6.0 tag, thanks.

**Comment by moy** [comment]
And here you are, a nice GitHub release ;-) https://github.com/git-multimail/git-multimail/releases/tag/1.6.0

Thanks for the report,
