### ISSUE TITLE
Possibility to use committer as "From" in generated mails

### ISSUE THREAD

**Issue by rhertzog** [git-multimail/git-multimail#31]
We have a limited set of committers and we like to see who commited directly in the "From" field. Please make it possible to use that identity in the From field ideally with a simple setting, otherwise at least with wrapper script.

Right now, it's not possible to override get_fromaddr() of the Environment because it doesn't get the details of the commit or from the changes.

**Comment by moy** [comment]
Fixed by #99.

**Comment by catalin-hritcu** [comment]
This works great, thanks a lot!
