### ISSUE TITLE
Possibility to disable the "refchange" mail when the push contains a single new commit.

### ISSUE THREAD

**Issue by rhertzog** [git-multimail/git-multimail#32]
I very much like how git-multimail sends individual commits as replies to a top-level "refchange" mail... except when the change is a simple update adding one commit. In that case I have two mails when one would have been more than enough.

Please change this behaviour or at least add an option to disable the "refchange" mail when the change is limited to a ref update adding a single commit. This option would only have an effect when commitlist / refchangelist are not used (or do not differ).

Thank you for your work on git-multimail, it was really needed!

**Comment by moy** [comment]
Hopefully, the code just merged should fix this. Feel free to reopen if not.
