### ISSUE TITLE
How to get announce email only?

### ISSUE THREAD

**Issue by luoqpolyvi** [git-multimail/git-multimail#39]
Hi, if I only set multimailhook.announceList to some email addresses, but left other list-related options unset, always got 

remote: The list of recipients for refchangelist is not configured.
remote: Please set one of the following:
remote:     "multimailhook.refchangelist"
remote:     "multimailhook.mailinglist"

in the case, no email got sent.

but I don't want every commit email being sent, only important tag/release notification.
Did I config anything wrong? Thanks.

**Comment by moy** [comment]
This is actually the documented behavior of gitolite:

http://gitolite.com/gitolite/git-config.html
http://gitolite.com/gitolite/git-config.html#an-important-warning-about-deleting-a-config-line

So we can do nothing about it in git-multimail. Thanks for the report anyway.
