### ISSUE TITLE
'unknown user' on Windows

### ISSUE THREAD

**Issue by fmuecke** [git-multimail/git-multimail#61]
When used on Windows system, the $USER environment is empty. Instead it should use
'$USERNAME' or something like '$USERNAME@$USERDOMAIN'.

For me replacing 

>>>>>
class GenericEnvironmentMixin(Environment):
    def get_pusher(self):
        return self.osenv.get('USER', 'unknown user')
 <<<<
with 
>>>
class GenericEnvironmentMixin(Environment):
    def get_pusher(self):
        return self.osenv.get('USERNAME', 'unknown user')
>>>
did the trick.

**Comment by sschuberth** [comment]
Note sure why this wasn't auto-closed by merging my PR, but [the fix is now in master](https://github.com/git-multimail/git-multimail/commit/a13c3c9a169727dea8bcb9c9a5c289732b4f4ca3).
