### ISSUE TITLE
Invalid encoding in From header

### ISSUE THREAD

**Issue by andreas-schwab** [git-multimail/git-multimail#70]
<http://permalink.gmane.org/gmane.emacs.diffs/127520> has this From header with an invalid UTF-8 character (it's actually Latin-1 encoded):

From: =?UTF-8?Q?Fabi=E1n_Ezequiel_Gallina?= <fgallina@gnu.org>

Note that the Reply-To header has the correct encoding.  (You can get the raw article via the NNTP interface.)

**Comment by moy** [comment]
git-multimail should properly encode all headers if fed with UTF-8 data. At least, I can get a properly encoded From: header out of the box on my UTF-8 system. So, right now, I do not think any action is needed on git-multimail's side, but please re-open if you can provide more information and if you think git-multimail can be improved.

Thanks for the report,
