### ISSUE TITLE
ConfigurationException: No email recipients configured!

### ISSUE THREAD

**Issue by kumarshantanu** [git-multimail/git-multimail#73]
I am getting the following stack trace when doing `git push origin <branchname>`, but subsequently running the same command gives no error, tells me `Everything up-to-date`. The push is ~~not~~ actually happening as I confirmed from the origin server.

Edit: The push is happening, but I get the stack trace nevertheless.

```
Counting objects: 3, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 312 bytes | 0 bytes/s, done.
Total 3 (delta 2), reused 0 (delta 0)
remote: Traceback (most recent call last):
remote:   File "hooks/post-receive", line 72, in <module>
remote:     environment = git_multimail.GenericEnvironment(config=config)
remote:   File "/var/tmp/git-multimail/git_multimail.py", line 2060, in __init__
remote:     super(ProjectdescEnvironmentMixin, self).__init__(**kw)
remote:   File "/var/tmp/git-multimail/git_multimail.py", line 1918, in __init__
remote:     **kw
remote:   File "/var/tmp/git-multimail/git_multimail.py", line 1959, in __init__
remote:     **kw
remote:   File "/var/tmp/git-multimail/git_multimail.py", line 1926, in __init__
remote:     super(FQDNEnvironmentMixin, self).__init__(**kw)
remote:   File "/var/tmp/git-multimail/git_multimail.py", line 1889, in __init__
remote:     config=config, **kw
remote:   File "/var/tmp/git-multimail/git_multimail.py", line 2031, in __init__
remote:     **kw
remote:   File "/var/tmp/git-multimail/git_multimail.py", line 1967, in __init__
remote:     super(PusherDomainEnvironmentMixin, self).__init__(**kw)
remote:   File "/var/tmp/git-multimail/git_multimail.py", line 1728, in __init__
remote:     config=config, **kw
remote:   File "/var/tmp/git-multimail/git_multimail.py", line 1719, in __init__
remote:     super(ConfigEnvironmentMixin, self).__init__(**kw)
remote:   File "/var/tmp/git-multimail/git_multimail.py", line 1897, in __init__
remote:     super(MaxlinesEnvironmentMixin, self).__init__(**kw)
remote:   File "/var/tmp/git-multimail/git_multimail.py", line 1854, in __init__
remote:     super(FilterLinesEnvironmentMixin, self).__init__(**kw)
remote:   File "/var/tmp/git-multimail/git_multimail.py", line 1998, in __init__
remote:     raise ConfigurationException('No email recipients configured!')
remote: git_multimail.ConfigurationException: No email recipients configured!
To git@cm-git.concurtech.net:core-services/core-shell.git
   c3b06f2..bf2999b  master -> master
```

What am I missing? I am using Git 2.3.1 on OS X and the origin is served by Gitlab.

**Comment by richardhansen** [comment]
`git_multimail.py` doesn't know who to send the emails to.  Try configuring your repository's `multimailhook.mailinglist` setting.

Remember that `git_multimail.py` is a `post-receive` hook, which runs after the push has already taken effect.  This is why the push happened even though you got the error, and it's also why redoing the push gave you `Everything up-to-date`.

**Comment by moy** [comment]
Thanks.

Still, we should catch the exception and provide an accurate error message.

**Comment by mhagger** [comment]
The error message is in the last line of the output:

    git_multimail.ConfigurationException: No email recipients configured!

If `git_multimail.py` is invoked directly, then `ConfigurationException`s are caught in `main()` and reported more gracefully. This error comes from using some kind of modified version of the example `post-receive` script that uses `git_multimail.py` as a library, circumventing `main()`. I was thinking that anybody who writes their own `post-receive` hook would know how to diagnose such errors and would probably want to see a full stack trace. Maybe I was wrong?

**Comment by moy** [comment]
Ah, indeed, I didn't notice that the backtrace was showing a custom hook. Then, indeed, it should be the caller's responsibility to catch the exception.
