### ISSUE TITLE
AttributeError: 'Push' object has no attribute 'environment'

### ISSUE THREAD

**Issue by jeskesen** [git-multimail/git-multimail#76]
In recent addition of "quiet" environment variable (commit 64dd4245a72abb3c864e0f6344a0e52d59ca349d) for suppressing the mailto list, an on existing environment structure is referenced inside Push.send_emails().

~/testing123$ git push origin master
Counting objects: 3, done.
Writing objects: 100% (3/3), 228 bytes | 0 bytes/s, done.
Total 3 (delta 0), reused 0 (delta 0)
remote: Traceback (most recent call last):
remote:   File "hooks/post-receive", line 90, in <module>
remote:     git_multimail.run_as_post_receive_hook(environment, mailer)
remote:   File "/home/jge/githook_test/hooks/git_multimail.py", line 2410, in run_as_post_receive_hook
remote:     push.send_emails(mailer, body_filter=environment.filter_body)
remote:   File "/home/jge/githook_test/hooks/git_multimail.py", line 2361, in send_emails
remote:     if not self.environment.quiet:
remote: AttributeError: 'Push' object has no attribute 'environment'
To /home/jge/githook_test/
 * [new branch]      master -> master

**Comment by edward-dauvergne** [comment]
The fix is rather easy, see pull request https://github.com/git-multimail/git-multimail/pull/79.
