### ISSUE TITLE
Evaluate use as a tool to send patches by mail to mailing lists

### ISSUE THREAD

**Issue by sschuberth** [git-multimail/git-multimail#82]
At Git Merge 2015 we had a discussion that [Setting up Git to send proper email patches is complicated](https://developer.atlassian.com/blog/2015/04/git-merge-2015-wrap/), and that it would be nice to have a tool that sends `[PATCH]` emails to a configurable email address when commits are pushed to a repository. I wonder whether doing so could be in the scope of `git-multimail`. Opinions?

In the best case there also would be an easy way to integrate this into GitHub.

**Comment by moy** [comment]
I'm not sure git-multimail would be the right tool for this for several reasons:

* The emails it sends are not meant to be applied by `git am`. The format of `git send-email` would be better.

* I'm not sure "push to send email" is the semantics we want. IMHO, it would be better to have a two-steps system like pull requests: push your code, make sure it's OK and click a "send patch series by email"

That's not a strong objection from me, though, and thanks for keeping the subject alive in any case ;-).

**Comment by sschuberth** [comment]
Of course using `git send-mail` (or better `git format-patch`, the sending part should probably be done by `git-multimail` itself) would be a requirement. I haven't look at `git-multimail`'s source code, but I thought it probably can use different formatter backends, and one of them could be `git format-patch`.

And personally, I definitely want "push to send email" semantics. That's exactly what my topic at Git Merge was about, *simplifying* the sending process, not adding another level of review / testing before sending the series. However, of course the "make sure it's OK" part could be done optionally anyway, now that GitHub integrates PRs so nicely with different CI and code quality tools that could perform various checks before the patch series goes out by mail.

**Comment by moy** [comment]
> it probably can use different formatter backends, and one of them could be git format-patch.

If you are to use `git send-email` to format the patches, then I think `git multimail` has very little benefit. Essentially, `git multimail` will help to:

* Compute the list of new commits. It's trivial in case of single-branch push, but more complex when you have several branches. I don't think one would want to do anything complex with a system to send emails to the mailing-list, so I'm not sure `git multimail` really helps here.

* Format emails. You can customize the format with templates, but AFAICT not use `format-patch` here.

* Format email headers (choose the From field, ...)

* Send the emails (using `sendmail` or SMTP)

> And personally, I definitely want "push to send email" semantics.

The difficulty IMHO is to compute the set of commits to send, and the associated risk is to do a trivial push that patch-bombs the list with tens of unrelated commits by mistake. That's where I would appreciate an extra step like "here's the set of commits I'm about to send, click OK to continue".

It becomes even more difficult when you force-push to send a v2: you want to resend the whole series, not just the new commits.

> However, of course the "make sure it's OK" part could be done optionally anyway

How would you see this step with push-to-send semantics?

(Again, don't take my answer badly, my questions are genuine questions and I do support your effort)

**Comment by moy** [comment]
There seem to be a good start here:

http://thread.gmane.org/gmane.comp.version-control.git
https://submitgit.herokuapp.com/

**Comment by sschuberth** [comment]
> How would you see this step with push-to-send semantics?

Thinking about it, this probably would need to be implemented by the caller of `git-multimail`, not by `git-multimail` itself.

I'm imagining a [webhook](https://developer.github.com/webhooks/) that

* is triggered on pull requests 
* can be configured to either call `git-multimail` right away, or
* can wait for a bot to comment on the code quality of the PR and then send, or
* creates a button on the PR's page to send mails manually.

**Comment by sschuberth** [comment]
Wow, [submitGit](https://submitgit.herokuapp.com/) sounds fantastic! Thanks a lot for bringing it to my attention. Closing this issue ... :-)
